---
driver_plugin: joyent
driver_config:
  joyent_username: <%= ENV['SDC_ACCOUNT'] %>
  joyent_keyfile: <%= ENV['SDC_KEY_FILE'] %>
  joyent_keyname: <%= ENV['SDC_KEY_ID'] %>
  joyent_url: <%= ENV['SDC_URL'] %>
  joyent_networks:
   - c0bf4505-75ca-41ea-a706-a8ca34a84f54
  joyent_image_id: a3c7b9ba-279d-11e6-aecd-07e1aa0cc545
  joyent_flavor_id: g4-general-4G
  joyent_version: '~7.0'

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 12.6.0
  client_rb:
    environment: kitchen

platforms:
- name: ubuntu-14.04

suites:
- name: client
  driver_config:
    vm_hostname: client
  encrypted_data_bag_secret_key_path: "test/integration/encrypted_data_bag_secret"
  run_list:
    - recipe[apt]
    - recipe[optoro_consul::client]
  attributes:
    apt:
      compile_time_update: true

- name: service
  driver_config:
    vm_hostname: service
  encrypted_data_bag_secret_key_path: "test/integration/encrypted_data_bag_secret"
  run_list:
    - recipe[apt]
    - recipe[optoro_consul::client]
    - recipe[optoro_consul::_service]
  attributes:
    apt:
      compile_time_update: true
    optoro_consul:
      service:
        name: 'test_service'
        port: 8080
        tags:
          - testing
        checks:
          - { script: 'echo true', interval: '5s' }
